add parcer and parcer tests, but without label attribute
AshFungor/graph-serializer pull request #13
Opened 2024-03-10 18:02 UTC by AndK17

2024-03-10 18:18 UTC, AshFungor requested changes
исправить

2024-03-10 18:18 UTC, AshFungor commented on data/proposal/.~lock.lexemes.pdf#
что это?

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/CMakeLists.txt
> +message(STATUS ${SRC_ROOT})
убери

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +#include "parcer.hpp"
инклюды сгруппировать, использовать "" только для файлов в той же директории

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +  {
скобочки поставлены по гейски

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +    std::cout << "Invalid graph type" << std::endl;
тут бросаем runtime_error

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +    THROW_INVALID_INPUT()
заменить на нормальную функцию

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +{
скобочки везде поставить как в моем файле

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +  if (event.graph.isWeighted() == false)
гей, ! в помощь

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +    parcer::LexemeParcer::shared.label = event.label;
лишний пробел

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +    if (event.graph.isDirectional() == true) flags |= common::opt::drc;
гей x2

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +  common::Graph graph;
табуляция 4 пробела

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +  for (auto s: inpt)
inpt -> input

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +      parcer::LexemeParcer::dispatch(parcer::InputGraphType{.graph = graph, .graph_type = std::any_cast<std::string>(s.value)});
сделай там конструкторы лучше

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +      if (graph.isDirectional() == true)
гей x3

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.cpp
> +      std::cout << "a" << std::endl;
что это за высер

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +#define THROW_INVALID_INPUT() \
вот это убрать и сделать нормальную функцию с исключением

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +#include <tinyfsm.hpp>
сгруппировать и прокомментировать

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +    std::string what_value_wait = "";
сложные типы инициальзировать не нужно, убери это

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +                                        std::string NodeID; };
перенос на новую строку за исключением потоков всегда делается на следующий уровень табуляции,
у тебя их тут как супрогов твой мамы

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +  struct InputIntValue : tinyfsm::Event { common::Graph& graph;
пробел перед common бесит тоже, сделай там новую строку

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +    virtual void react(InputGraphType const &) {};
const InputGraphType&, везде

2024-03-10 18:18 UTC, AshFungor commented on src/parcer/parcer.hpp
> +  struct OpenSquareBracket : LexemeParcer
перед всеми наследованиями напиши public

2024-03-10 18:18 UTC, AshFungor commented on src/tests/parcer-test.cpp
> +    std::vector<common::Lexeme> inpt {
inpt -> input

2024-03-10 18:18 UTC, AshFungor commented on src/tests/parcer-test.cpp
> +// testing target
нормальный коммент сделай

2024-03-10 18:18 UTC, AshFungor commented on src/tests/parcer-test.cpp
> +    {common::LexemeType::GRAPH_START_LABEL, std::string("graph")},
std::string{} ебать высер

2024-03-10 18:18 UTC, AshFungor commented on src/tests/parcer-test.cpp
> +        {common::LexemeType::CLOSED_CURLY_BRACKET}};
}; на новую строку

2024-03-10 18:18 UTC, AshFungor commented on src/tests/parcer-test.cpp
> +    EXPECT_EQ(graph.areConnected(std::string("a"), std::string("b")), true);
EXPECT_TRUE

2024-03-10 18:28 UTC, AndK17 commented on data/proposal/.~lock.lexemes.pdf#
убрал еще до коммента

2024-03-10 18:46 UTC, AndK17 commented on src/tests/parcer-test.cpp
> +    {common::LexemeType::GRAPH_START_LABEL, std::string("graph")},
без этого any_cast не работает

2024-03-10 19:11 UTC, AndK17 commented on src/parcer/parcer.hpp
> +    virtual void react(InputGraphType const &) {};
![image](https://github.com/AshFungor/graph-serializer/assets/57502612/fd5bb88c-a98a-46c8-ad91-d4d82c5a2667)
я как то больше доке доверяю

2024-03-10 19:30 UTC, AndK17 commented on src/parcer/parcer.cpp
> +      parcer::LexemeParcer::dispatch(parcer::InputGraphType{.graph = graph, .graph_type = std::any_cast<std::string>(s.value)});
нет

2024-03-11 10:52 UTC, AshFungor commented on src/parcer/parcer.cpp
> +      parcer::LexemeParcer::dispatch(parcer::InputGraphType{.graph = graph, .graph_type = std::any_cast<std::string>(s.value)});
Да

2024-03-11 10:54 UTC, AshFungor commented on src/parcer/parcer.hpp
> +    virtual void react(InputGraphType const &) {};
Да там странно, давай не как Андрей сделаем

2024-03-11 10:54 UTC, AshFungor commented on src/tests/parcer-test.cpp
> +    {common::LexemeType::GRAPH_START_LABEL, std::string("graph")},
:(

2024-03-11 10:56 UTC, AshFungor approved these changes
Молодец Андрей

2024-03-11 10:56 UTC, merged