[scripts][proposal] add pdf building script and lexemal graph
AshFungor/graph-serializer pull request #3
Opened 2024-01-29 14:15 UTC by AndK17

[scripts][proposal] add pdf building script and lexemal graph

2024-01-29 17:21 UTC, AshFungor requested changes

2024-01-29 17:21 UTC, AshFungor commented on scripts/gv_build.sh
> +
добавь тут printf или echo с коротким описанием работы скрипта, чтоб verbose был так сказать

2024-01-29 17:21 UTC, AshFungor commented on scripts/gv_build.sh
> +printf 'Building...\n'
вот это убрать соответсвенно (одного верхнего принта хватит)

2024-01-29 17:21 UTC, AshFungor commented on data/proposal/lexemas.gv
> +	digraph_node [shape = "ellipse" label = "digraph"]
entrypoint

2024-01-29 17:21 UTC, AshFungor commented on data/proposal/lexemas.gv
> +	graph_name -> open_curly_bracket
все ребра подписать

2024-01-29 17:21 UTC, AshFungor commented on data/proposal/lexemas.gv
> +	edge_node [shape = "ellipse" label = "-> / --"]
--> / -- подпиши ребро, название ноды - edge

2024-01-30 13:24 UTC, AshFungor requested changes

2024-01-30 13:24 UTC, AshFungor commented on data/proposal/lexemes.gv
> +	node_id [shape = "ellipse" label = "node ID/{"]
давай напишем node ID / node group begin

2024-01-30 13:24 UTC, AshFungor commented on data/proposal/lexemes.gv
> +	after_node_id [shape = "ellipse" label = "}/(->/--)/["]
node group end / edge / attribute list start

2024-01-30 13:24 UTC, AshFungor commented on data/proposal/lexemes.gv
> +	remember_attr_value -> node_id [label="]"]
а где выход из парсера? там по схеме вроде выходит что мы никогда не сможем закончить

2024-01-30 13:24 UTC, AshFungor commented on data/proposal/lexemes.gv
> +	open_curly_bracket -> node_id [label="{"]
graph start

2024-02-02 08:11 UTC, AndK17 commented on data/proposal/lexemes.gv
> +	node_id [shape = "ellipse" label = "node ID/{"]
неа, это будут не лексемы

2024-02-02 10:25 UTC, AshFungor approved these changes

2024-02-02 17:17 UTC, AshFungor commented
подождем что Владимир Игоревич скажет

2024-02-05 12:12 UTC, AshFungor requested changes
надо убрать это из pr в другой

2024-02-06 15:45 UTC, AshFungor approved these changes

2024-02-24 18:26 UTC, AshFungor commented
ручной тест парсера на примере _data/examples/binary-tree.gv_:
- digraph
- (remember type: directional graph)
- {
- node id (root)
- (remember node id: root)
- [
- label
- =
- value (root)
- (remember attribute value: root)
- ]
- l_child
- ... (аналогично для 7 другихб там только значения меняются)
- root 
- (remember node id: root)
- ->
- l_child
- (remember node id: l_child)
- space
- expect node id?

Исправить ситуацию с пробелом, нужно корректно парсить аттрибуты связи + добавь к связи в аттрибуты label тк можно использовать и weight и label для одной цели и по-хорошему уметь надо в оба

2024-02-24 21:02 UTC, AshFungor commented
ручной тест парсера на примере _data/examples/binary-tree.gv_ (опять):
- digraph
- (remember type: directional graph)
- {
- node id (root)
- (remember node id: root)
- [
- label
- =
- value (root)
- (remember attribute value: root)
- ]
- l_child
- ... (аналогично для 7 других, там только значения меняются)
- root 
- (remember node id: root)
- ->
- l_child
- (remember node id: l_child)
- [
- weight (label)
- =
- value (12)
- (remember attribute value: 12)
- ]
- ... (аналогично)
- }
end

OK

2024-02-24 21:15 UTC, merged